### ISSUE TITLE
Debugging with VSCode

### ISSUE THREAD

**Issue by marc-cardona** [stevejhiggs/aws-lambda-typescript#1]
Hello there,

I'm just starting to develop aws lambda functions locally with node (TypeScript) and I found this repo very interesting; **congratulations for this great tool!** Unfortunately, I am unable to configure Visual Studio Code for debugging. 

Currently you already mention that it is mandatory to set protocol attribute to "inspector", but it would be very helpful if you could include in the documentation an example of the debug configuration for VSCode.

Thank you,
Regards.

**Comment by stevejhiggs** [comment]
Thanks marc. I'll add some images to the readme but to help you for now:

Go to the debug tab in visual studio
at the top where it says "debug" and probably "no configurations" there should be a gear icon. Click it and you should be taken to your launch.json file that will look something like:

```
"version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\index.js",
            "outFiles": [
                "${workspaceRoot}/out/**/*.js"
            ]
        }
    ]
```

add the line `"protocol": "inspector",` to this so we end up with something like:

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "name": "Launch Program",
            "program": "${workspaceRoot}\\index.js",
            "outFiles": [
                "${workspaceRoot}/out/**/*.js"
            ]
        }
    ]
}
```

Then you should be able to debug as normal. Also if you use node version 8 or greater it will default to this and the above will be not needed.

Thanks
Steve

**Comment by marc-cardona** [comment]
Steve, Thank you very much for your quick reply.

Still having troubles debugging. I have changed my "launch.json" and I am always getting the following error:

<img width="473" alt="captura de pantalla 2017-06-15 a las 20 44 17" src="https://user-images.githubusercontent.com/29413369/27196763-18970b1c-520c-11e7-90be-46a8cbff6282.png">
I have been trying to update my node version to 8.1.2 but I'm still receiving the same "Unexpected token export" error.

Do you know where might be the problem?

Thank you again
Marc

**Comment by stevejhiggs** [comment]
Hi marc, I'll take a look at it when I get some time this weekend (I've a 1 year old daughter and that means I only get a few hours here or there). I'm about to do a significant update and I'll give better examples

**Comment by marc-cardona** [comment]
Ok Steve, thanks for your patience ;)
I look forward to the next update.

**Comment by stevejhiggs** [comment]
Hi marc, if you update to latest then any newly init'd functions should be fine. 

To fix an already existing function:

- overwrite your tsconfig and tslint files with the ones in https://github.com/stevejhiggs/aws-lambda-typescript/tree/master/templates.
- Update the index.ts to follow the one in https://github.com/stevejhiggs/aws-lambda-typescript/tree/master/templates as there are some changes in the imports and returns.

**Comment by marc-cardona** [comment]
Thank you Steve, everything working.
Marc

**Comment by omatrot** [comment]
Hello, could you please explain what you mean by 'debug as normal' ? Following your init steps and starting debugging with F5 ends with the following error:
>Cannot launch program '.../typescript lambda/index.ts' because corresponding JavaScript cannot be found.
I understand that the code should be already transpiled...
