### ISSUE TITLE
Compile failure causes bad deployment

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#12]
If you run "gulp lambda:deploy" and the Typescript code has an error, it does not stop, but instead deploys something that just doesn't work (e.g., causes 502 gateway errors when invoked through API Gateway).

My latest was: [tsl] ERROR in blah/blah/blah.ts(778,17)
      TS1005: ',' expected.

I would much rather that if the Typescript code has an error, the whole process stops and nothing gets deployed to AWS.  Can an error in the build stage cause the deploy to abort?

(I know I could run the build step separately, but I'm not willing to wait for *THREE* NPM install runs in the usual case where everything works...)

**Comment by stevejhiggs** [comment]
Woof that took a while :) But for what it's worth this is fixed in 5.1.1
