### ISSUE TITLE
Doesn't work with Gulp 4

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#14]
It's getting increasingly hard to stick with Gulp 3.

Can you publish a build of gulp-webpack-typescript-pipeline with the Gulp 4 support and then update aws-lambda-typescript to use it?

**Comment by stevejhiggs** [comment]
This is what happens when I don't check my notifications 😂 on it

**Comment by stevejhiggs** [comment]
version 4 with gulp4 support was just published
