### ISSUE TITLE
How to disable ignorable TS errors for a line?

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#19]
Way back on v3, I would use e.g. `// tslint:disable-line` and things like that.

I just updated to v4 and those notations seem to be ignored now.  How do you now suppress a typescript error that you know is not a breaking problem (e.g. let vs const) for a particular block of code?  The tslint docs I see still seem to indicate that should work, so does the current build process use something other than tslint or force it to ignore inline annotations?

**Comment by ammulder** [comment]
Ah, looks like it switched to eslint.  I've been able to switch my in-code configuration over...  Now just need to see if I can migrate my project-wide configuration.  :)

**Comment by stevejhiggs** [comment]
Good catch, I caught myself out when I upgraded the deps and didn't realise. I've added a note to the CHANGELOG https://github.com/stevejhiggs/aws-lambda-typescript/commit/f5b629fa8a9a74aa84ef14775b5673efd3066d6d.

Thanks for the heads up!
