### ISSUE TITLE
Error with generated lambda handler

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#2]
When I build with "gulp lambda:package" and upload the generated ZIP file as my Lambda function, I get this error in the Lambda console:

"errorMessage": "Handler 'handler' missing on module 'index'"

I tried renaming "func" to "handler" but that didn't do it.

I also tried changing my lambda config from "index.handler" to "index.default" but then I just get:

"errorMessage": "Handler 'default' missing on module 'index'"

Any suggestions?

**Comment by ammulder** [comment]
I also tried using "gulp lambda:deploy" to deploy to a new Lambda function, instead of my existing one, and I get the same error:

{
  "errorMessage": "Handler 'default' missing on module 'index'"
}

As far as I can tell, when Webpack processes the code, it breaks the "export" statement?  It's not clear to me what the actual exports in the processed "index.js" are versus what AWS Lambda is looking for.

**Comment by ammulder** [comment]
Seems like it is solved by adding libraryTarget: "commonsjs2" in the Webpack config in gulp-webpack-typescript-pipeline:
```
    output: {
      path: path.join(options.outputDir),
      libraryTarget: "commonjs2",
      filename: '[name].js'
    },
```

Is there some way to provide that setting as an override from this module?

**Comment by stevejhiggs** [comment]
nice catch! I suspect some internal upgrades have broken the upload process. Give me a sec

**Comment by stevejhiggs** [comment]
ok, please update to 0.0.11 and this should all be fixed. You dont need to regenerate the function it is enough just to regenerate the package. Thanks again for the help
