### ISSUE TITLE
Copy .npmrc during deploy

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#22]
First time trying aws-lambda-typescript on a project pulling dependencies from a custom NPM repository.  The settings for it are in `.npmrc` in the project directory.  Unfortunately during a `gulp lambda:deploy`, the `package.json` is copied but `.npmrc` is not, so the final build fails due to missing dependencies.

Can `.npmrc` be copied along with the other config files (if it is present in the project dir)?

**Comment by stevejhiggs** [comment]
Great idea, I'll try to sort it over the next few days

**Comment by stevejhiggs** [comment]
Hi, this is now resolved in version 5.1.0

**Comment by ammulder** [comment]
Great, thanks!
