### ISSUE TITLE
Lambda Environment Variables Broken

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#4]
Apparently Webpack strips out `process.env` calls by default (or substitutes dev-time values or something), which means that a Lambda attempting to use environment variables defined in the Lambda console just gets nothing (or the wrong value).

To fix this, the webpack config in gulp-webpack-typescript-pipeline needs this:
```
var webpack = require('webpack');
...
plugins: [
      new webpack.DefinePlugin({
        'process.env': 'process.env'
      })
    ]
```
That results in the `process.env` calls being passed through to the final processed code.

I guess again, that can be some kind of option that aws-lambda-typescript sets...  I'm not sure whether you'd rather it be something like "preserveEnvironmentCalls" or have it accept a list of plugins or what.

**Comment by stevejhiggs** [comment]
I think I'm just going to need to rework this area :)

**Comment by ammulder** [comment]
OK, well, I'll be interested to see your solution.  I have a Lambda calling Cognito and I put the Cognito pool ID and client ID into environment variables...  For now I have to remember to go change the webpack config by hand in node_modules...  :)

**Comment by stevejhiggs** [comment]
Ok, 0.0.15 should fix your issue. I have also set the output target for webpack to be "node" which should fix another lot of potential issues. I think I will revisit the need for webpack though....I'm not sure the project really gains anything from it.
