### ISSUE TITLE
Lambda handler function name is mangled by Webpack+UglifyJS when doing a release build

### ISSUE THREAD

**Issue by a0m721** [stevejhiggs/aws-lambda-typescript#6]
The name mangling will result in the lambda handler function, as specified in 'lambda-config.js', not being found when attempting to run the lambda.

It looks like all the UglifyJS config is applied from 'node_modules/gulp-webpack-typescript-pipeline/webpack.config.release.js', leaving no control for the developer to modify or override settings.

Have you encountered this problem and how do I overcome it?

**Comment by a0m721** [comment]
I looked at the uglified output to find that the handler function is assigned as the module's default export. So if 'lambda-config.js' specifies "handler: 'index.default'", then all is well.

Perhaps this gotcha should be clarified in the readme.

**Comment by stevejhiggs** [comment]
Thanks. I'll add the clarification

**Comment by stevejhiggs** [comment]
This is now the default in the generated files. Hopefully that should clear up the issue.
