### ISSUE TITLE
MySQL doesn't work

### ISSUE THREAD

**Issue by ammulder** [stevejhiggs/aws-lambda-typescript#7]
So I've now tried a Lambda with RDS (MySQL).

If Webpack (or uglify or whatever is under the covers) gets its hands on the Node MySQL driver, it throws a protocol error and fails when you try to connect.

I can exclude MySQL from the Webpack build by adding it to 'externals' list in tsOptions in index.js here.  But then I need to manually create the zip with the Webpack-output index.js and also a node-modules directory I construct with the subset of packages that mysql needs.  (And then it works fine, no protocol error.)

You once mentioned perhaps ditching Webpack, which I assume would solve this.  But I'm also open to any other solution -- is there some better way to say I want mysql and its dependencies (of which there are perhaps 7) excluded from the mangling but included as node_modules in the ZIP?

Worst case, if I could provide my own list of externals to registerBuildGulpTasks that would help because I wouldn't have to edit the externals list in the code for this lib in the node_modules of every MySQL-using lambda.  And I could just put my own script in place to call lambda:build, make the modified ZIP, and then call lambda:upload.

**Comment by ammulder** [comment]
If there's not a near-term solution, could you at least let me pass in a list of externals in registerBuildGulpTasks, and add anything specified there to /aws-sdk/ in the tsOptions object?

**Comment by stevejhiggs** [comment]
I'll try to take a look this weekend

**Comment by stevejhiggs** [comment]
The newly released v1.0.0 should fix this. 

node_modules is now left well alone and is just packaged up the in the resulting zip. This should solve a large number of issues as well as improving compilation times.
